### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by wu-kai** [FE-help/help#1]
@oaying   你试试把问题在这里面进行留言

**Comment by wu-kai** [comment]
![image](https://user-images.githubusercontent.com/12909883/147807881-1a177245-41e4-4f4d-9b39-4b0d79e3ce14.png)
  

在这里留言   然后点 comment

**Comment by oaying** [comment]
测试测试
![u=2314600222,1003014148 fm=253 fmt=auto app=138 f=JPEG](https://user-images.githubusercontent.com/93694046/147807942-bfbdb0d0-e366-4a5c-a9e3-593fd80c25e4.png)

**Comment by wu-kai** [comment]
对的  这里就当微信  解决代码问题了

**Comment by oaying** [comment]
![8e1976d8805d93a1f742e5ef38a89ac](https://user-images.githubusercontent.com/93694046/147807984-546c14e4-d9fe-4770-8282-2325e06ff342.png)
![5c04e672e7c88dabe389cc37d893396](https://user-images.githubusercontent.com/93694046/147807988-e6cc50f5-35ba-423a-a76a-b9fa6fbc0cfa.png)
接着来 他说他这个样子写了 还是没有数据回填

**Comment by oaying** [comment]
我觉得要不让他试试不要写async和await呢？

**Comment by wu-kai** [comment]
这个东西有点恼火，  建议直接用placeholder...    使用后端返回的  ['10', '1001', '4235'] 这个数组去拼凑成   '中国/四川/成都'  这样的字符串  放到placeholder上面去

**Comment by oaying** [comment]
他这个问题点是出在哪儿的呢

**Comment by wu-kai** [comment]
不晓得。。。。我先上个厕所  然后写个demo试试看

**Comment by oaying** [comment]
没事 我直接喊他不写async和await试试看了  因为我这边做这个就没问题 也是那样绑定的

**Comment by wu-kai** [comment]
![image](https://user-images.githubusercontent.com/12909883/147811039-28cfc6d3-9437-4d90-b323-6a8591a31d47.png)


像这样，把最后一级的value值，作为v-model的值就行了

**Comment by wu-kai** [comment]
fixed


已经完成的Issue 会被关闭

**Comment by wu-kai** [comment]
![image](https://user-images.githubusercontent.com/12909883/147811133-7089b45c-0740-45b1-ae2b-0bff775d18da.png)


关闭的issue在这里查看

**Comment by oaying** [comment]
![image](https://user-images.githubusercontent.com/93694046/147811834-9aa1e3f2-611e-48b1-a9d1-9272247780fe.png)
我是通过btntext的值来更改全选和取消全选的状态的 但是现在还有一个问题 我点单个取消的的时候 就不是全部选中了 按道理来说应该btnText的值就应该变成全选  你看我写的 我准备在onupload生命周期里面做  就是我注释的那个  但是那样子写就报一个超过最大堆栈内存的警告

**Comment by wu-kai** [comment]
![image](https://user-images.githubusercontent.com/12909883/147812198-1b7b58da-2b4d-4d2a-bf36-343d5e9c779d.png)

为什么没有分号。。
